from __future__ import annotations

import asyncio
import logging
import re
from typing import Optional

from app import devin_client, github_client
from app.config import settings
from app.database import get_pending_sessions, update_session

logger = logging.getLogger(__name__)


async def poll_loop() -> None:
    """Background task: poll every N seconds and update session states."""
    while True:
        await asyncio.sleep(settings.poll_interval_seconds)
        try:
            pending = await get_pending_sessions()
            if pending:
                logger.info("Polling %d active session(s)", len(pending))
            for session in pending:
                await _check_session(session)
        except Exception:
            logger.exception("Unexpected error in poll loop")


async def _check_session(session: dict) -> None:
    sid = session["session_id"]
    try:
        data = await devin_client.get_session(sid)
    except Exception:
        logger.exception("Failed to fetch Devin session %s", sid)
        return

    devin_status = data.get("status", "running")
    logger.debug("Session %s → devin status: %s", sid, devin_status)

    if devin_status == "stopped":
        pr_url = _extract_pr_url(data)
        new_status = "completed" if pr_url else "failed"
        await update_session(sid, new_status, pr_url)
        await _post_outcome(session, new_status, pr_url)
        logger.info("Session %s finished → %s  PR: %s", sid, new_status, pr_url)

    elif devin_status == "blocked":
        await update_session(sid, "blocked")
        await _post_outcome(session, "blocked", None)
        logger.warning("Session %s is blocked and needs human input", sid)


def _extract_pr_url(data: dict) -> Optional[str]:
    for field in ("pull_request_url", "pr_url"):
        if url := data.get(field):
            return url
    # Fall back to scanning the session title/summary for a GitHub PR URL
    for field in ("title", "summary", "structured_output"):
        text = str(data.get(field, ""))
        match = re.search(r"https://github\.com/\S+/pull/\d+", text)
        if match:
            return match.group(0)
    return None


async def _post_outcome(
    session: dict, status: str, pr_url: Optional[str]
) -> None:
    repo = session["repo"]
    issue_num = session["issue_number"]
    devin_url = session.get("devin_url") or ""

    if status == "completed" and pr_url:
        body = (
            "## Devin has resolved this issue ✅\n\n"
            f"A pull request has been automatically created: {pr_url}\n\n"
            f"**Devin session:** {devin_url}\n\n"
            "_This PR was generated by automated Devin remediation. "
            "Please review before merging._"
        )
    elif status == "blocked":
        body = (
            "## Devin needs assistance ⚠️\n\n"
            "The automated Devin session is blocked and requires human input.\n\n"
            f"**Devin session:** {devin_url}\n\n"
            "Please review the session and provide guidance."
        )
    else:
        body = (
            "## Automated remediation failed ❌\n\n"
            "The Devin session completed but did not produce a pull request.\n\n"
            f"**Devin session:** {devin_url}\n\n"
            "Please review the session log for details."
        )

    try:
        await github_client.post_comment(repo, issue_num, body)
    except Exception:
        logger.exception("Failed to post comment on %s#%d", repo, issue_num)
